================================================ test session starts =================================================
platform linux -- Python 3.6.2, pytest-3.2.0, py-1.5.3, pluggy-0.4.0
rootdir: /home/aheyer/py3-opsim/gitdir/ts_scheduler, inifile:
plugins: session2file-0.1.9, forked-0.2, xdist-1.20.1, flake8-0.9.1

collecting 0 items
collecting 3 items
collecting 3 items

collected 3 items 

test_model.py ..F

====================================================== FAILURES ======================================================
____________________________________ TestSchedulerModel.test_send_valid_settings _____________________________________

self = <tests.model.test_model.TestSchedulerModel testMethod=test_send_valid_settings>

    def test_send_valid_settings(self):
    
        m = Model()
    
>       m.sal_start()

test_model.py:35: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <lsst.ts.scheduler.model.Model object at 0x7f17f52810f0>

    def sal_start(self):
>       self.sal.start()
E       AttributeError: 'NoneType' object has no attribute 'start'

../../python/lsst/ts/scheduler/model.py:38: AttributeError
========================================= 1 failed, 2 passed in 1.29 seconds =========================================
